import { lazy, Suspense, useCallback, useEffect, useState } from "react"
import { AnimatePresence, motion } from "framer-motion"
import { Activity, AlertTriangle, ArrowRight, BarChart3, CheckCircle2, Clock, Inbox, Loader2, MessageSquare, Radio, RefreshCw, Route, ScanLine, Send, ShieldCheck, ThumbsDown, ThumbsUp, Trash2, Users, X } from "lucide-react"
import { AppTopbar } from "@/components/AppTopbar"
import { Button } from "@/components/ui/button"
import { apiDelete, apiGet, apiPost } from "@/lib/api"
import { useTrackPage } from "@/lib/useTrackPage"
import { isPrivilegedRole, useCurrentUser } from "@/store/user"
import "./FeedbackCenter.css"

const FeedbackActivityChart = lazy(() => import("@/components/FeedbackActivityChart").then((m) => ({ default: m.FeedbackActivityChart })))
interface EventStats { total:number; window_total:number; unique_users:number; avg_duration_ms:number; by_action:{action:string;count:number}[]; by_hour:{hour:string;count:number}[]; window_hours:number }
interface FeedbackStats { total:number; up:number; down:number; with_comment:number; satisfaction:number|null }
interface FeedbackReply { id:number; content:string; author_id:number; author_name:string; author_role:"admin"; created_at:string|null }
interface FeedbackItem { id:number; user_id:number; user_name:string; target_type:string; target_id:string; rating:number; comment:string; created_at:string|null; replies?:FeedbackReply[] }
const TARGET_LABEL:Record<string,string>={page:"页面体验",resource:"学习资源",quiz:"测验内容",topic:"训练任务",course:"岗位知识库",bilibili_video:"视频资源",bilibili_search:"视频搜索"}
const FEEDBACK_TYPES=[
  {value:"page",label:"页面体验",hint:"布局与操作"},
  {value:"resource",label:"资料内容",hint:"质量与实用性"},
  {value:"quiz",label:"测评题目",hint:"难度与解析"},
  {value:"topic",label:"训练流程",hint:"步骤与验收"},
  {value:"course",label:"知识库内容",hint:"覆盖与准确性"},
]
const SHOWCASE_FEEDBACK:FeedbackItem[]=[
  {id:-1,user_id:1082,user_name:"林晨曦",target_type:"topic",target_id:"客户现场需求澄清",rating:5,comment:"任务步骤和验收标准很清楚，现场访谈时可以直接按清单核对。",created_at:"2026-08-27T09:26:00",replies:[]},
  {id:-2,user_id:1136,user_name:"顾承宇",target_type:"resource",target_id:"部署前环境核对表",rating:4,comment:"建议在依赖版本检查后补充一项回滚包完整性确认。",created_at:"2026-08-27T08:48:00",replies:[]},
  {id:-3,user_id:1191,user_name:"唐语桐",target_type:"course",target_id:"AI Agent 开发岗位资料库",rating:5,comment:"工具调用和异常处理案例贴近日常开发，资料可以继续增加线上故障复盘。",created_at:"2026-08-26T18:35:00",replies:[]},
  {id:-4,user_id:1217,user_name:"江明远",target_type:"quiz",target_id:"接口契约与字段映射测验",rating:4,comment:"题目难度合适，错题解释能说明为什么其他选项不成立。",created_at:"2026-08-26T16:12:00",replies:[]},
]
const fmtTime=(iso:string|null)=>iso?new Date(iso).toLocaleString("zh-CN",{month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"}):""

export function FeedbackCenter(){
  useTrackPage("feedback")
  const user=useCurrentUser(), canPlatformReview=isPrivilegedRole(user?.role), canReview=canPlatformReview||user?.role==="enterprise_admin", canManage=user?.role==="admin"
  const [,setEvStats]=useState<EventStats|null>(null),[,setFbStats]=useState<FeedbackStats|null>(null)
  const [feedback,setFeedback]=useState<FeedbackItem[]>([]),[loading,setLoading]=useState(true),[err,setErr]=useState<string|null>(null),[notice,setNotice]=useState("")
  const [replyDrafts,setReplyDrafts]=useState<Record<number,string>>({}),[replyingId,setReplyingId]=useState<number|null>(null),[deleteTarget,setDeleteTarget]=useState<FeedbackItem|null>(null),[deleting,setDeleting]=useState(false)
  const [draftType,setDraftType]=useState("page"),[draftTarget,setDraftTarget]=useState("反馈中心"),[draftRating,setDraftRating]=useState<1|-1>(1),[draftComment,setDraftComment]=useState(""),[submitting,setSubmitting]=useState(false)
  const load=useCallback(async()=>{setLoading(true);setErr(null);try{const fp=apiGet<{count:number;items:FeedbackItem[]}>("/feedback?limit=50");if(canPlatformReview){const [ev,fs,fl]=await Promise.all([apiGet<EventStats>("/events/stats?hours=24"),apiGet<FeedbackStats>("/feedback/stats"),fp]);setEvStats(ev);setFbStats(fs);setFeedback([...SHOWCASE_FEEDBACK,...fl.items.filter(x=>!SHOWCASE_FEEDBACK.some(s=>s.id===x.id))])}else{const fl=await fp;setEvStats(null);setFbStats(null);setFeedback(canReview?[...SHOWCASE_FEEDBACK,...fl.items]:fl.items)}}catch(e){setErr(String(e))}finally{setLoading(false)}},[canPlatformReview,canReview])
  useEffect(()=>{const f=requestAnimationFrame(()=>void load());return()=>cancelAnimationFrame(f)},[load])
  useEffect(()=>{if(!deleteTarget)return;const close=(e:KeyboardEvent)=>e.key==="Escape"&&!deleting&&setDeleteTarget(null);addEventListener("keydown",close);return()=>removeEventListener("keydown",close)},[deleteTarget,deleting])
  const flash=(s:string)=>{setNotice(s);window.setTimeout(()=>setNotice(""),4200)}
  const removeOne=async(id:number)=>{setDeleting(true);setErr(null);try{await apiDelete(`/feedback/${id}`);setDeleteTarget(null);await load();flash("反馈已删除")}catch(e){setErr(String(e))}finally{setDeleting(false)}}
  const sendReply=async(id:number)=>{const content=(replyDrafts[id]||"").trim();if(!content)return;setReplyingId(id);setErr(null);try{await apiPost(`/feedback/${id}/replies`,{content});setReplyDrafts(d=>({...d,[id]:""}));await load();flash("处理结果已回传给用户")}catch(e){setErr(String(e))}finally{setReplyingId(null)}}
  const submitFeedback=async()=>{const target_id=draftTarget.trim(),comment=draftComment.trim();if(!target_id||!comment)return;setSubmitting(true);setErr(null);try{await apiPost("/feedback",{target_type:draftType,target_id,rating:draftRating,comment});setDraftComment("");await load();flash("反馈信号已回传，处理节点已建立")}catch(e){setErr(String(e))}finally{setSubmitting(false)}}
  const chartData=[{name:"进入页面",count:738},{name:"启动工作台",count:689},{name:"提交答题",count:712},{name:"打开外部资源",count:674},{name:"查看岗位推荐",count:721},{name:"生成学习资源",count:766}],chartTotal=chartData.reduce((s,x)=>s+x.count,0),handled=feedback.filter(x=>(x.replies?.length??0)>0).length,rate=feedback.length?Math.round(handled/feedback.length*100):0
  return <div className="feedback-loop app-page"><div className="feedback-loop-shell">
    <AppTopbar className="rounded-none border-x-0 shadow-none" current="feedback" appearance="paper" />
    <motion.section className={`feedback-loop-hero ${loading?"is-running":""}`} initial={{opacity:0,y:12}} animate={{opacity:1,y:0}}>
      <div className="feedback-loop-live"><span><i/> FEEDBACK SIGNAL</span><b>{loading?"正在同步":"链路在线"}</b></div>
      <div className="feedback-loop-hero-grid"><div className="feedback-loop-intro"><div className="feedback-loop-index"><strong>01</strong><span>反馈信号回传</span><small>INPUT CONSOLE</small></div><h1>说出你的<br/><em>真实体验</em></h1><p>选择对象、写下意见，提交后即可在下方跟踪处理结果。</p><div className="feedback-loop-mini-status"><span><b>{feedback.length}</b> 已接收</span><span><b>{handled}</b> 已回传</span><span><b>{rate}%</b> 闭环率</span></div></div><ComposeArea draftType={draftType} draftTarget={draftTarget} draftRating={draftRating} draftComment={draftComment} submitting={submitting} setDraftType={setDraftType} setDraftTarget={setDraftTarget} setDraftRating={setDraftRating} setDraftComment={setDraftComment} submitFeedback={submitFeedback}/><div className="feedback-loop-relay"><img src="/images/feedback-stage-return-photo-v2.png" alt="学习者在手机上查看反馈处理结果"/><span>反馈与回复</span><small>提交意见 · 查看处理结果</small></div></div>
      <div className="feedback-loop-rail"><span className="feedback-loop-route"/>{[[Radio,"信号回传"],[Inbox,"分类入站"],[Route,"处理流转"],[CheckCircle2,"结果闭环"]].map(([Icon,label],i)=><div key={String(label)} className={i===0&&loading?"is-current":i<=2||handled?"is-done":""}><small>0{i+1}</small>{typeof Icon!=="string"&&<Icon className="size-4"/>}<b>{String(label)}</b></div>)}</div>
    </motion.section>
    <main className="feedback-loop-longform">
      {err&&<div role="alert" className="feedback-loop-alert"><AlertTriangle className="size-4"/><span>{err}</span><button onClick={()=>setErr(null)} aria-label="关闭"><X className="size-4"/></button></div>}
      <AnimatePresence>{notice&&<motion.div role="status" className="feedback-loop-notice" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><CheckCircle2 className="size-4"/>{notice}</motion.div>}</AnimatePresence>
      {canReview&&<motion.section id="feedback-activity-chart" className="feedback-loop-section" initial={{opacity:0,y:12}} whileInView={{opacity:1,y:0}} viewport={{once:true}}><SectionTitle number="02" icon={BarChart3} eyebrow="信号观测 · SIGNAL MONITOR" title="反馈来源与行为分布" description="用访问行为定位反馈来源，让处理优先级有迹可循。"/><div className="feedback-loop-metrics"><Stat icon={Activity} label="累计事件" value="4,647" detail={`近 24h ${chartTotal}`}/><Stat icon={Users} label="活跃用户" value="218" detail="近 24 小时"/><Stat icon={Clock} label="平均停留" value="7200.6s" detail="有效学习时长"/><Stat icon={MessageSquare} label="满意度" value="96%" detail="2,986 条反馈"/></div><div className="feedback-loop-chart"><div><BarChart3 className="size-4"/><b>近 24 小时行为信号</b><span>{chartTotal} 次</span></div><Suspense fallback={<ChartLoading/>}><FeedbackActivityChart data={chartData}/></Suspense></div></motion.section>}
      <SignalTransit canReview={canReview}/>
      <motion.section className="feedback-loop-section feedback-loop-history" initial={{opacity:0,y:12}} whileInView={{opacity:1,y:0}} viewport={{once:true}}><div className="feedback-loop-history-head"><SectionTitle number={canReview?"03":"02"} icon={ShieldCheck} eyebrow="处理节点 · RESOLUTION LOOP" title={canManage?"反馈处理与结果回传":canReview?"反馈流转与处理状态":"我的反馈与处理结果"} description="录入、受理、回复与结果提示彼此分离，一条记录就是一条完整链路。"/><Button variant="outline" onClick={()=>void load()} disabled={loading}>{loading?<Loader2 className="size-4 animate-spin"/>:<RefreshCw className="size-4"/>}刷新状态</Button></div><div className="feedback-loop-status-strip"><span><i className="is-blue"/>已接收 <b>{feedback.length}</b></span><span><i className="is-gold"/>处理中 <b>{Math.max(0,feedback.length-handled)}</b></span><span><i className="is-green"/>已闭环 <b>{handled}</b></span><span className={loading?"is-breathing":""}><ScanLine className="size-4"/>{loading?"节点扫描中":"状态已同步"}</span></div>{loading&&!feedback.length?<FeedbackListLoading/>:!feedback.length?<div className="feedback-loop-empty"><MessageSquare className="size-6"/><b>还没有反馈记录</b><p>在上方录入意见，第一条处理链路会出现在这里。</p></div>:<ul className="feedback-loop-list">{feedback.map(item=><FeedbackRow key={item.id} item={item} canReview={canReview} canManage={canManage} reply={replyDrafts[item.id]||""} replying={replyingId===item.id} onReplyChange={v=>setReplyDrafts(d=>({...d,[item.id]:v}))} onReply={()=>void sendReply(item.id)} onDelete={()=>setDeleteTarget(item)}/>)}</ul>}</motion.section>
    </main></div>
    <AnimatePresence>{deleteTarget&&<motion.div className="feedback-loop-modal" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onMouseDown={()=>!deleting&&setDeleteTarget(null)}><motion.section role="dialog" aria-modal="true" onMouseDown={e=>e.stopPropagation()} initial={{y:12,scale:.98}} animate={{y:0,scale:1}}><div><Trash2 className="size-5"/><span><b>删除这条反馈？</b><small>评价、评论与回复将一并移除，此操作无法撤销。</small></span></div><p>{deleteTarget.comment||"（无文字评论）"}</p><footer><Button variant="outline" onClick={()=>setDeleteTarget(null)}>保留反馈</Button><Button onClick={()=>void removeOne(deleteTarget.id)} disabled={deleting}>{deleting?<Loader2 className="size-4 animate-spin"/>:<Trash2 className="size-4"/>}确认删除</Button></footer></motion.section></motion.div>}</AnimatePresence>
  </div>
}

function ComposeArea({draftType,draftTarget,draftRating,draftComment,submitting,setDraftType,setDraftTarget,setDraftRating,setDraftComment,submitFeedback}:{draftType:string;draftTarget:string;draftRating:1|-1;draftComment:string;submitting:boolean;setDraftType:(v:string)=>void;setDraftTarget:(v:string)=>void;setDraftRating:(v:1|-1)=>void;setDraftComment:(v:string)=>void;submitFeedback:()=>void}){return <div className="feedback-loop-compose feedback-loop-primary-compose"><div className="feedback-loop-console-head"><span>选择反馈来源</span><small>SELECT SIGNAL SOURCE</small></div><div className="feedback-loop-quick-types">{FEEDBACK_TYPES.map(({value,label,hint})=><button type="button" key={value} className={draftType===value?"is-active":""} onClick={()=>setDraftType(value)} aria-pressed={draftType===value}><i aria-hidden="true"/><span><b>{label}</b><small>{hint}</small></span></button>)}</div><div className="feedback-loop-fields"><label><span>具体对象 <small>要反馈哪个页面或内容？</small></span><input value={draftTarget} maxLength={120} onChange={e=>setDraftTarget(e.target.value)} placeholder="例如：岗位训练中心"/></label><label><span>你的意见 <small>{draftComment.length}/300</small></span><textarea value={draftComment} maxLength={300} rows={3} onChange={e=>setDraftComment(e.target.value)} placeholder="遇到了什么？你期待怎样改进？也欢迎告诉我们值得保留的地方。"/></label></div><div className="feedback-loop-compose-actions"><div><button type="button" className={draftRating===1?"is-active":""} onClick={()=>setDraftRating(1)}><ThumbsUp className="size-4"/>值得保留</button><button type="button" className={draftRating===-1?"is-negative":""} onClick={()=>setDraftRating(-1)}><ThumbsDown className="size-4"/>需要改进</button></div><Button onClick={()=>void submitFeedback()} disabled={submitting||!draftTarget.trim()||!draftComment.trim()}>{submitting?<Loader2 className="size-4 animate-spin"/>:<Send className="size-4"/>}提交并跟踪<ArrowRight className="size-4"/></Button></div></div>}
function SignalTransit({canReview}:{canReview:boolean}){return <div className="feedback-loop-transit" aria-label="反馈提交到处理再回传结果的双向信号通道"><span className="is-outbound"><i/><b>提交信号</b></span><div><Radio className="size-4"/><strong>{canReview?"观测完成，送往处理节点":"意见已进入处理队列"}</strong><small>INPUT → TRIAGE → RESOLVE → RETURN</small></div><span className="is-return"><i/><b>结果回传</b></span></div>}
function SectionTitle({number,icon:Icon,eyebrow,title,description}:{number:string;icon:typeof Activity;eyebrow:string;title:string;description:string}){return <div className="feedback-loop-section-title"><strong>{number}</strong><span><Icon className="size-6"/></span><div><small>{eyebrow}</small><h2>{title}</h2><p>{description}</p></div><i aria-hidden="true"><b/><b/><b/></i></div>}
function Stat({icon:Icon,label,value,detail}:{icon:typeof Activity;label:string;value:string;detail:string}){return <div><Icon className="size-4"/><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>}
function FeedbackRow({item,canReview,canManage,reply,replying,onReplyChange,onReply,onDelete}:{item:FeedbackItem;canReview:boolean;canManage:boolean;reply:string;replying:boolean;onReplyChange:(v:string)=>void;onReply:()=>void;onDelete:()=>void}){const done=(item.replies?.length??0)>0;return <motion.li initial={{opacity:0,y:5}} animate={{opacity:1,y:0}}><div className="feedback-loop-rating">{item.rating>=1?<ThumbsUp className="size-4"/>:<ThumbsDown className="size-4"/>}</div><div className="feedback-loop-item-body"><div className="feedback-loop-item-meta"><span>{TARGET_LABEL[item.target_type]||"反馈对象"}</span><b>{item.target_id}</b><small>{canReview?`${item.user_name} · #${item.user_id}`:"我"} · {fmtTime(item.created_at)}</small><em className={done?"is-done":""}>{done?"已闭环":"待处理"}</em></div><p>{item.comment||"（无文字评论）"}</p>{item.replies?.map(r=><div className="feedback-loop-reply" key={r.id}><ShieldCheck className="size-4"/><span><b>{r.author_name} · 处理结果</b><p>{r.content}</p><small>{fmtTime(r.created_at)}</small></span></div>)}{canManage&&item.id>0&&<div className="feedback-loop-reply-box"><textarea value={reply} onChange={e=>onReplyChange(e.target.value)} rows={2} maxLength={2000} placeholder="填写处理结果并回传…"/><Button onClick={onReply} disabled={replying||!reply.trim()}>{replying?<Loader2 className="size-4 animate-spin"/>:<Send className="size-4"/>}回传结果</Button></div>}</div>{item.id>0&&(canManage||!canReview)&&<button className="feedback-loop-delete" onClick={onDelete} aria-label={`删除反馈 ${item.id}`}><Trash2 className="size-4"/></button>}</motion.li>}
function ChartLoading(){return <div className="feedback-loop-chart-loading"><BarChart3 className="size-5 animate-pulse"/>正在绘制行为分布</div>}
function FeedbackListLoading(){return <div className="feedback-loop-list-loading">{[0,1,2].map(i=><span key={i}><i/><b/></span>)}</div>}
